# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://poczujbluesa.pl
title: Poczuj Bluesa
email: olga@poczujbluesa.pl
author: Olga Jaśkowska
locale: pl_PL
image: http://poczujbluesa.pl/img/og-page-image2.jpg
description: Gordonowskie zajęcia umuzykalniające w Warszawie dla dzieci i niemowląt od pierwszy miesięcy życia.
copyright: 'Copyright &copy; 2016 Poczuj Bluesa. All Rights Reserved.'
#credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://facebook.com/poczuj.bluesa
