# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://poczujbluesa.pl
title: Poczuj Bluesa
email: olga@poczujbluesa.pl
author: Olga Jaśkowska
locale: pl_PL
image: http://poczujbluesa.pl/img/og-page-image2.jpg
description: Zajęcia gordonowskie dla dzieci w Warszawie. Umuzykalniamy dzieci od pierwszych miesięcy życia! Gordonki prowadzimy na Bielanach, Żoliborzu, Śródmieściu. Nasze zajęcie umuzykalniające dla dzieci opieramy o teorię uczenia się muzyki i badania prof. E.E. Gordona.
copyright: 'Copyright &copy; 2016 Poczuj Bluesa. All Rights Reserved.'
#credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://facebook.com/poczuj.bluesa
