# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://poczujbluesa.pl
title: Gordonki Poczuj Bluesa
email: olga@poczujbluesa.pl
author: Olga Jaśkowska
locale: pl_PL
image: http://poczujbluesa.pl/img/og-page-image2.jpg
description: Misją Poczuj Bluesa jest umuzykalnianie dzieci od pierwszych miesięcy życia tak, aby potrafiły się w przyszłości cieszyć muzyką i mogły w pełni wykorzystać swój muzyczny potencjał. Gordonki (gordonowskie zajęcia umuzykalniające) prowadzimy aktualnie w Warszawie na Żoliborzu i w Śródmieściu. Zapraszamy!
copyright: 'Copyright &copy; 2016 Poczuj Bluesa. All Rights Reserved.'
#credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://facebook.com/poczuj.bluesa
